# Generated by Django 3.1.5 on 2021-01-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20210123_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approval',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='bag',
            field=models.CharField(choices=[('Chicken', 'Chicken Bag'), ('Tuna', 'Tuna Bag'), ('Veg', 'Veg Bag')], default='Chicken', max_length=20),
        ),
    ]
