# Generated by Django 3.1.5 on 2021-01-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20210124_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='nuid',
            new_name='username',
        ),
    ]
