# Generated by Django 3.1.5 on 2021-01-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20210124_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=' ', max_length=150, unique=True)),
                ('item_quantity', models.IntegerField()),
                ('item_description', models.TextField()),
            ],
        ),
    ]
